server:
  port: 8080

spring:
  application:
    name: keykomi-blog-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blog}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:hard_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  # Jackson configuration
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

# JWT Configuration and S3
app:
  jwt:
    secret: ${JWT_SECRET:759234752903847529340572839042798}
    expiration-ms: ${JWT_EXPIRATION:5184000000} # 60 days in milliseconds
  s3:
    bucket: ${AWS_BUCKET_NAME:storage-for-blog}

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.keykomi.webblog: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      access: read_only
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application info
info:
  app:
    name: ${spring.application.name}
    version: ${project.version:@project.version@}
    description: Keykomi Blog Service with JWT Authentication
    jwt-expiration-days: 60